In [ ]:
from keras.datasets import mnist
(x, y), (test_x, test_y) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
from sklearn.model_selection import train_test_split
train_x, val_x, train_y, val_y = train_test_split(x, y, test_size = 0.2, stratify = y)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.losses import categorical_crossentropy, sparse_categorical_crossentropy

In [ ]:
m = Sequential()
m.add(Flatten(input_shape = train_x.shape[1:])) # 데이터의 갯수
m.add(Dense(100, activation = 'relu'))
m.add(Dense(10, activation = 'softmax'))
m.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 100)               78500     
                                                                 
 dense_1 (Dense)             (None, 10)                1010      
                                                                 
Total params: 79,510
Trainable params: 79,510
Non-trainable params: 0
_________________________________________________________________


In [ ]:
m.compile(loss = 'sparse_categorical_crossentropy', metrics = ['acc'])

In [ ]:
hy = m.fit(train_x, train_y, validation_data = (val_x, val_y), epochs = 50)

#CNN

In [ ]:
import numpy as np
w = np.array([2, 1, 5, 3])
x = np.array([2, 8 ,3, 7, 1, 2, 0, 4, 5])

In [ ]:
len(x), len(w)

(9, 4)

In [ ]:
np.flip(w)

array([3, 5, 1, 2])

In [ ]:
w_r = w[::-1]

In [ ]:
x[:4]

array([2, 8, 3, 7])

In [ ]:
for i in range(6):
    print(x[i:i+4]@w_r)

63
48
49
28
21
20


In [ ]:
from scipy.signal import correlate
correlate(x, w, mode = 'valid')
correlate(x, w, mode = 'same')
correlate(x, w, mode = 'full')

array([ 6, 34, 51, 48, 57, 24, 25, 16, 39, 29, 13, 10])

In [ ]:
from scipy.signal import correlate2d

In [ ]:
w = np.array([[2, 0],
              [0, 0]])
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [ ]:
correlate2d(x, w, mode = 'valid')

array([[ 2,  4],
       [ 8, 10]])

In [ ]:
correlate2d(x, w, mode = 'same')

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
correlate2d(x, w, mode = 'full')

array([[ 0,  0,  0,  0],
       [ 0,  2,  4,  6],
       [ 0,  8, 10, 12],
       [ 0, 14, 16, 18]])

In [ ]:
import numpy as np
from scipy.signal import correlate, correlate2d
import tensorflow as tf

In [ ]:
x = np.array([[1., 2., 3., 4.],
              [5., 6., 7., 8.],
              [9., 10., 11., 12.],
              [13., 14., 15., 16.]])
x = x.reshape(1, 4, 4, 1) # (인스턴스 수, 가로축, 세로축, 채널)

In [ ]:
p_out = tf.nn.max_pool2d(x, ksize = 2, strides = 2, padding = 'VALID')
p_out

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float64, numpy=
array([[[[ 6.],
         [ 8.]],

        [[14.],
         [16.]]]])>

In [ ]:
p_out = tf.nn.max_pool2d(x, ksize = 2, strides = 2, padding = 'SAME')
p_out

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 6.],
         [ 8.]],

        [[14.],
         [16.]]]], dtype=float32)>