In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
df=pd.read_csv("data.csv")
X=df[['D_length',	'D_weight']]
y=df['y']
X.shape,y.shape

((49, 2), (49,))

In [3]:
s=StandardScaler().fit(X)
s_X=s.transform(X)

In [4]:
tr_x,tt_x,tr_y,tt_y=train_test_split(s_X,y,random_state=1,test_size=0.3)

In [5]:
tr_x.shape,tt_x.shape,tr_y.shape,tt_y.shape

((34, 2), (15, 2), (34,), (15,))

In [6]:
m=LogisticRegression()
m.fit(tr_x,tr_y)

LogisticRegression()

In [7]:
m.score(tr_x,tr_y),m.score(tt_x,tt_y)

(1.0, 1.0)

In [8]:
m.coef_,m.intercept_

(array([[-1.73618958, -1.26804725]]), array([-2.3556859]))

In [9]:
from sklearn.metrics import f1_score,accuracy_score,precision_score,recall_score

In [10]:
py=m.predict(tt_x)

In [11]:
f1_score(tt_y,py)

1.0

In [12]:
print(f"""정확도:{accuracy_score(tt_y,py)}
정밀도:{precision_score(tt_y,py)}
민감도:{recall_score(tt_y,py)}
f1점수:{f1_score(tt_y,py)}""")

정확도:1.0
정밀도:1.0
민감도:1.0
f1점수:1.0


In [13]:
from sklearn.metrics import classification_report
print(classification_report(tt_y,py))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



In [14]:
m.decision_function(tt_x)

array([-4.93981229, -6.71753987,  2.05688104,  1.36665938, -1.85261398,
       -2.37056395,  1.95373466, -6.22771801,  1.83731347, -6.1722594 ,
       -6.30891186,  2.09152346, -4.48406614,  2.30874843, -4.26178372])

In [17]:
#m.classes_[m.predict()]

In [18]:
tt_y

27    0
34    0
39    1
48    1
2     0
3     0
42    1
29    0
45    1
30    0
31    0
38    1
21    0
35    1
19    0
Name: y, dtype: int64

Q1 타이타닉 데이터를 이용하여 이진 분류기를 설계 하시오

In [19]:
import seaborn as sns
df=sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [21]:
df1=df.iloc[:,:8]
df1

survived  pclass     sex   age  sibsp  parch     fare embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [22]:
c_d=df1[['pclass','sex','sibsp','parch','embarked']]
c_d

pclass     sex  sibsp  parch embarked
0         3    male      1      0        S
1         1  female      1      0        C
2         3  female      0      0        S
3         1  female      1      0        S
4         3    male      0      0        S
..      ...     ...    ...    ...      ...
886       2    male      0      0        S
887       1  female      0      0        S
888       3  female      1      2        S
889       1    male      0      0        C
890       3    male      0      0        Q

[891 rows x 5 columns]

In [23]:
from sklearn.preprocessing import OneHotEncoder
o_h_e=OneHotEncoder()
o_h_e.fit(c_d)

OneHotEncoder()

In [24]:
o_h_e.feature_names_in_

array(['pclass', 'sex', 'sibsp', 'parch', 'embarked'], dtype=object)

In [25]:
o_h_e.categories_

[array([1, 2, 3]),
 array(['female', 'male'], dtype=object),
 array([0, 1, 2, 3, 4, 5, 8]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array(['C', 'Q', 'S', nan], dtype=object)]

In [26]:
l=[]
for i in range(len(o_h_e.feature_names_in_)):
  l+=[o_h_e.feature_names_in_[i]+"_"+str(결합문자) for 결합문자 in o_h_e.categories_[i]]
l

['pclass_1',
 'pclass_2',
 'pclass_3',
 'sex_female',
 'sex_male',
 'sibsp_0',
 'sibsp_1',
 'sibsp_2',
 'sibsp_3',
 'sibsp_4',
 'sibsp_5',
 'sibsp_8',
 'parch_0',
 'parch_1',
 'parch_2',
 'parch_3',
 'parch_4',
 'parch_5',
 'parch_6',
 'embarked_C',
 'embarked_Q',
 'embarked_S',
 'embarked_nan']

In [27]:
o_h_e.get_feature_names_out()

array(['pclass_1', 'pclass_2', 'pclass_3', 'sex_female', 'sex_male',
       'sibsp_0', 'sibsp_1', 'sibsp_2', 'sibsp_3', 'sibsp_4', 'sibsp_5',
       'sibsp_8', 'parch_0', 'parch_1', 'parch_2', 'parch_3', 'parch_4',
       'parch_5', 'parch_6', 'embarked_C', 'embarked_Q', 'embarked_S',
       'embarked_nan'], dtype=object)

In [28]:
o_h_e.categories_[3]

array([0, 1, 2, 3, 4, 5, 6])

In [29]:
x=o_h_e.transform(c_d)
x.toarray().shape

(891, 23)

In [30]:
in_x=x.toarray()
o_h_e_df=pd.DataFrame(in_x,columns=o_h_e.get_feature_names_out())
o_h_e_df

pclass_1  pclass_2  pclass_3  sex_female  sex_male  sibsp_0  sibsp_1  \
0         0.0       0.0       1.0         0.0       1.0      0.0      1.0   
1         1.0       0.0       0.0         1.0       0.0      0.0      1.0   
2         0.0       0.0       1.0         1.0       0.0      1.0      0.0   
3         1.0       0.0       0.0         1.0       0.0      0.0      1.0   
4         0.0       0.0       1.0         0.0       1.0      1.0      0.0   
..        ...       ...       ...         ...       ...      ...      ...   
886       0.0       1.0       0.0         0.0       1.0      1.0      0.0   
887       1.0       0.0       0.0         1.0       0.0      1.0      0.0   
888       0.0       0.0       1.0         1.0       0.0      0.0      1.0   
889       1.0       0.0       0.0         0.0       1.0      1.0      0.0   
890       0.0       0.0       1.0         0.0       1.0      1.0      0.0   

     sibsp_2  sibsp_3  sibsp_4  ...  parch_1  parch_2  parch_3  parch_4  \
0        0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
1        0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
2        0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
3        0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
4        0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
..       ...      ...      ...  ...      ...      ...      ...      ...   
886      0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
887      0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
888      0.0      0.0      0.0  ...      0.0      1.0      0.0      0.0   
889      0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
890      0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   

     parch_5  parch_6  embarked_C  embarked_Q  embarked_S  embarked_nan  
0        0.0      0.0         0.0         0.0         1.0           0.0  
1        0.0      0.0         1.0         0.0         0.0           0.0  
2        0.0      0.0         0.0         0.0         1.0           0.0  
3        0.0      0.0         0.0         0.0         1.0           0.0  
4        0.0      0.0         0.0         0.0         1.0           0.0  
..       ...      ...         ...         ...         ...           ...  
886      0.0      0.0         0.0         0.0         1.0           0.0  
887      0.0      0.0         0.0         0.0         1.0           0.0  
888      0.0      0.0         0.0         0.0         1.0           0.0  
889      0.0      0.0         1.0         0.0         0.0           0.0  
890      0.0      0.0         0.0         1.0         0.0           0.0  

[891 rows x 23 columns]

In [31]:
o_h_e.feature_names_in_

array(['pclass', 'sex', 'sibsp', 'parch', 'embarked'], dtype=object)

In [32]:
df1.drop(o_h_e.feature_names_in_,axis=1)

survived   age     fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
886         0  27.0  13.0000
887         1  19.0  30.0000
888         0   NaN  23.4500
889         1  26.0  30.0000
890         0  32.0   7.7500

[891 rows x 3 columns]

In [33]:
df1_1=df1.drop(o_h_e.feature_names_in_,axis=1)
df1_1

survived   age     fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
886         0  27.0  13.0000
887         1  19.0  30.0000
888         0   NaN  23.4500
889         1  26.0  30.0000
890         0  32.0   7.7500

[891 rows x 3 columns]

In [40]:
o_h_e

OneHotEncoder()

In [39]:
end_load_df=pd.concat([df1_1,o_h_e_df],axis=1)
end_load_df

survived   age     fare  pclass_1  pclass_2  pclass_3  sex_female  \
0           0  22.0   7.2500       0.0       0.0       1.0         0.0   
1           1  38.0  71.2833       1.0       0.0       0.0         1.0   
2           1  26.0   7.9250       0.0       0.0       1.0         1.0   
3           1  35.0  53.1000       1.0       0.0       0.0         1.0   
4           0  35.0   8.0500       0.0       0.0       1.0         0.0   
..        ...   ...      ...       ...       ...       ...         ...   
886         0  27.0  13.0000       0.0       1.0       0.0         0.0   
887         1  19.0  30.0000       1.0       0.0       0.0         1.0   
888         0   NaN  23.4500       0.0       0.0       1.0         1.0   
889         1  26.0  30.0000       1.0       0.0       0.0         0.0   
890         0  32.0   7.7500       0.0       0.0       1.0         0.0   

     sex_male  sibsp_0  sibsp_1  ...  parch_1  parch_2  parch_3  parch_4  \
0         1.0      0.0      1.0  ...      0.0      0.0      0.0      0.0   
1         0.0      0.0      1.0  ...      0.0      0.0      0.0      0.0   
2         0.0      1.0      0.0  ...      0.0      0.0      0.0      0.0   
3         0.0      0.0      1.0  ...      0.0      0.0      0.0      0.0   
4         1.0      1.0      0.0  ...      0.0      0.0      0.0      0.0   
..        ...      ...      ...  ...      ...      ...      ...      ...   
886       1.0      1.0      0.0  ...      0.0      0.0      0.0      0.0   
887       0.0      1.0      0.0  ...      0.0      0.0      0.0      0.0   
888       0.0      0.0      1.0  ...      0.0      1.0      0.0      0.0   
889       1.0      1.0      0.0  ...      0.0      0.0      0.0      0.0   
890       1.0      1.0      0.0  ...      0.0      0.0      0.0      0.0   

     parch_5  parch_6  embarked_C  embarked_Q  embarked_S  embarked_nan  
0        0.0      0.0         0.0         0.0         1.0           0.0  
1        0.0      0.0         1.0         0.0         0.0           0.0  
2        0.0      0.0         0.0         0.0         1.0           0.0  
3        0.0      0.0         0.0         0.0         1.0           0.0  
4        0.0      0.0         0.0         0.0         1.0           0.0  
..       ...      ...         ...         ...         ...           ...  
886      0.0      0.0         0.0         0.0         1.0           0.0  
887      0.0      0.0         0.0         0.0         1.0           0.0  
888      0.0      0.0         0.0         0.0         1.0           0.0  
889      0.0      0.0         1.0         0.0         0.0           0.0  
890      0.0      0.0         0.0         1.0         0.0           0.0  

[891 rows x 26 columns]

Q1 타이타닉 데이터를 이용하여 이진 분류기를 설계 하시오

1.데이터 수집

2.데이터 전처리

1. 결측치 처리
2. 이상치 처리

3. 범주형처리

4. 범위처리

5. 전처리된 데이터 데이터 프레임 화

3.학습

4.테스트 및 검증