In [3]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]],int)
#arr[5]

In [ ]:
print(arr)
arr.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
a = [[1,2],[3,4],[5]]
d = np.array(a)
print(d)

[list([1, 2]) list([3, 4]) list([5])]


<ipython-input-11-faf173016a2d>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d = np.array(a)


In [ ]:
np.array(range(1,10,2))

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
a1 = np.arange(2,11,2)
print(a1)
a1.shape

[ 2  4  6  8 10]


(5,)

In [ ]:
np.nan

nan

In [ ]:
np.ones((1,1,1,1,1,1,1,1,1,1,1,1,1,1))

array([[[[[[[[[[[[[[1.]]]]]]]]]]]]]])

In [5]:
a = np.ones(10,int)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
a2 = a.reshape(2, 5)
a2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a2.reshape(-1, 2)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
a + 1

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

스칼라 연산(자리 연산)

In [ ]:
a + b

array([ 2,  4,  6,  8, 10])

In [ ]:
a.dot(b)

55

In [7]:
a = np.array([[1,2,3,4,5]])
b = a.T
a, b

(array([[1, 2, 3, 4, 5]]),
 array([[1],
        [2],
        [3],
        [4],
        [5]]))

In [ ]:
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
a + b

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [ ]:
a.dot(b)

array([[55]])

In [ ]:
a@b

array([[55]])

In [ ]:
a = np.array([[1,2],[3,4]])
a.T

array([[1, 3],
       [2, 4]])

In [8]:
l = [1,2,3,4,5]
l2 = l[::2]
l2[0] = 1
l2, l

([1, 3, 5], [1, 2, 3, 4, 5])

In [10]:
a = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(a)
a[:,]
#b = a[1:6:2]
# b[0] =  10
# a, b

[[1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]]


array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [ ]:
l = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
a2 = np.array(l)
a2[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

In [ ]:
a2[::2,::3]

array([[ 1,  4],
       [11, 14]])

In [ ]:
l = [[0,1,2,3,4], [5,6,7,8,9],[10,11,12,13,14]]
arr = np.array(l)
arr[0:3:2,3:4]

array([[ 3],
       [13]])

넘파이의 인덱스는 ,로 차원을 이야기 할 수 있다.

In [11]:
arr = np.zeros((2,3))
arr2 = np.arange(1,101,2)
arr, arr2

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
        69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]))

In [ ]:
#단위행렬 생성
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
print(arr)
arr.sum(axis = (0,1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


105

In [ ]:
import numpy as np
from PIL import Image

def rle_to_mask(rle, shape):
    """
    RLE 형식의 마스크를 이미지로 변환하는 함수
    :param rle: RLE 형식의 마스크
    :param shape: 이미지의 형태 (높이, 너비)
    :return: 변환된 이미지
    """
    mask = np.zeros(shape[0] * shape[1], dtype=np.uint8)
    rle_list = rle.split()
    starts = rle_list[::2]
    lengths = rle_list[1::2]

    for start, length in zip(starts, lengths):
        start = int(start) - 1
        length = int(length)
        mask[start:start + length] = 255

    mask = mask.reshape((shape[0], shape[1]))
    #픽셀값 범위조정
    mask_image = Image.fromarray(mask, mode='L')

    return mask_image

import os
import cv2
from tqdm import tqdm

def csv_to_mask_img(reader,image_path,save_path):
    """
    csv파일 안의 RLE 형식의 문자열 마스크를 이미지로 변환하는 함수
    :param csv_file_list: csv 파일 리스트
    :param image_path: 이미지 경로
    :param save_path: 변환된 이미지 저장 경로
    """
    image_list=os.listdir(image_path)

    cnt=0
    for line in tqdm(reader):
        # 1행은 넘김
        if line[1]=="img_path":
            continue
        else:
            image= cv2.imread(image_path+image_list[cnt], cv2.IMREAD_GRAYSCALE) #불러오기
            rle=line[2]
            h,w=image.shape
            img_shape=(h,w)

            # RLE 형식의 마스크를 이미지로 변환
            mask_image = rle_to_mask(rle, img_shape)
            mask_image.save(f"{save_path}{line[0]}.png")

        cnt+=1

# 다각형 좌표로 바운딩 박스 좌표 계산하는 함수
def calculate_bounding_box(coordinates):
    x_values = [coord[0] for coord in coordinates]
    y_values = [coord[1] for coord in coordinates]

    min_x = min(x_values)
    min_y = min(y_values)
    max_x = max(x_values)
    max_y = max(y_values)

    width = max_x - min_x
    height = max_y - min_y

    return min_x, min_y, width, height

# RLE 디코딩 함수
def rle_decode(rle_mask, height, width):
    mask_array = np.zeros(height * width, dtype=np.uint8)
    rle_segments = np.asarray(rle_mask.split(), dtype=int)
    starts = rle_segments[::2]
    lengths = rle_segments[1::2]
    for start, length in zip(starts, lengths):
        end = start + length
        mask_array[start:end] = 255
    mask_array = mask_array.reshape((height, width), order="F")
    return mask_array

from skimage.measure import find_contours

def extract_contours_from_rle(rle_mask, height, width):
    # RLE 마스크를 배열로 변환
    mask_array = rle_decode(rle_mask, height, width)

    # 객체의 윤곽선 좌표를 찾기 위해 이진 이미지로 변환
    binary_image = (mask_array > 0).astype(np.uint8)

    # 윤곽선 좌표 추출
    contours = find_contours(binary_image, 0.5, fully_connected="low")

    # 좌표 값 조정 (0.5 픽셀 더하기)
    adjusted_contours = [contour + 0.5 for contour in contours]

    print(type(adjusted_contours))
    return adjusted_contours

import base64
import json

def csv_to_json(reader, image_path,json_path):
    oldLine=reader[1][0] # 첫번째 이미지 이름을 기본값으로 설정
    new_data={}
    shapes_list = []

    image_list=os.listdir(image_path)
    cnt=0
    for line in tqdm(reader): # csv 한 행마다
        # print("line:",line)

        # 1행은 넘김
        if line[1]=="img_path":
            continue

        points=[]
        # # 건물이 존재하지 않을때의 정보 저장
        # if int(line[1])<0:
        #     shape_type="none"
        #     label="background"
        #     points="none"
        #     bbox="none"

        # # 건물이 존재할때
        # else:
        shape_type="polygon"
        label="building"
        # if oldLine==line[0]:

        # # 다각형 좌표값 추출
        # line[2]=line[2].replace("POLYGON ((","")
        # line[2]=line[2].replace("))","")
        # line[2] = line[2].split(" 0,")

        # for i in range(len(line[2])):
        #     point=line[2][i].split(" ")
        #     points.append([int(float(point[0])),int(float(point[1]))])

        # x, y, width, height = calculate_bounding_box(points)
        # bbox=[x,y,width,height]
        image= cv2.imread(image_path+image_list[cnt], cv2.IMREAD_GRAYSCALE) #불러오기

        h,w=image.shape
        # img_shape=(h,w)

        # 윤곽선 좌표 추출 (contours 변수에 저장되어 있다고 가정)
        contours = extract_contours_from_rle(line[2], h, w)
        print("contours:",contours)

        # contours=contours.all()
        x, y, width, height = calculate_bounding_box(contours)
        bbox=[x,y,width,height]

        shape_data={
            'points':points,
            'label':label,
            'bbox' : bbox,
            'shape_type': shape_type
        }

        if oldLine!=line[0]:
            shapes_list=[]

        shapes_list.append(shape_data)

        print("shapes_list:",shapes_list)
        # imagePath="3band_"+line[0]+".tif"

        # # 이미지 데이터를 Base64로 인코딩
        # with open(image_path+imagePath, "rb") as f:
        #     image_data = f.read()
        #     encoded_image_data = base64.b64encode(image_data).decode("utf-8")

        # with Image.open(image_path+imagePath) as img:
        #     width,height=img.size

        # new_data = {
        # 'shapes': shapes_list,
        # 'imagePath': imagePath,
        # 'imageData':encoded_image_data,
        # 'imageHeight' : width,
        # 'imageWidth' : height
        # }
        # oldLine=line[0]

        json_file=image_list[cnt]+".json"
        json_file=json_file.replace(".png","")
        # print(json_file)

        # 수정된 JSON 파일 저장
        output_json_file_path =json_path+json_file
        # print(output_json_file_path)
        with open(output_json_file_path, "w") as f:
            json.dump(new_data, f)

        cnt+=1


import os
import csv
import building_seg as seg

csv_file="./open/train.csv"
# train_csv="train.csv"

train_image_path="./open/train_img/"
rle_image_path="./open/rle_img/"
json_path="./open/train_json/"

reader=[]
# csv 파일 정보 접근
if os.path.isfile(csv_file): # csv 파일 존재할때만 실행
    with open(csv_file, 'r') as f: # csv 열기
        reader = csv.reader(f) # csv 파일 읽기
        reader=list(reader) # csv 파일 list로 변경

    # seg.csv_to_mask_img(reader,train_image_path,rle_image_path)
    seg.csv_to_json(reader, train_image_path, json_path)

In [13]:
v1=np.array([1,1,1])
v2=np.array([2,2,2])
np.hstack([v1,v2])
a2=np.vstack([v1,v2])
a3=np.hstack([v1,v2])
a2, a3

(array([[1, 1, 1],
        [2, 2, 2]]),
 array([1, 1, 1, 2, 2, 2]))

In [16]:
a = np.array([[1, 0], [3, 4]])
a

array([[1, 0],
       [3, 4]])

In [18]:
np.all(a, axis = 0)

array([ True, False])

In [19]:
np.any(a)

True