In [2]:
import numpy as np
l = [0,1,2,3,4,5,6,7,8,9,10,11]
a = np.array(l).reshape(2, -1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

numpy.인덱싱<br>
array[고차원,저차원]

In [ ]:
a[0,0]

0

numpy 슬라이싱(접근경로 만들기) - <접근 경로 단순화>
* 슬라이싱과 인덱싱은 혼합해서 사용이 가능하다.
* 넘파이 배열의 구조에 따라 축의 갯수가 다르다.
* 인덱싱과 슬라이싱은 배열의 축의 갯수에 따라 동작 갯수가 정해진다

In [ ]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a[1:6:3, 3:]

array([[3, 4, 5]])

#넘파이의 연산

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

스칼라

In [ ]:
b = [[1],[1]]
b

[[1], [1]]

In [ ]:
a + [[1],[1]] #[[1,1,1,1,1,1],[1,1,1,1,1,1]] -> 1차원 축 확장/ 2차원 축확장 브로드캐스팅

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

벡터

In [ ]:
v1 = np.array([1,1,1,1,1,1]) # [v1, v1] -> 2차원 축 확장
a + v1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
v2 = np.array([[1],[1]])
a + v2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

행렬

In [ ]:
a3 = a.reshape(3,2,2)
a3

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [ ]:
l = [1,1,1]
m1 = np.array(l).reshape(3,1)
m1

array([[1],
       [1],
       [1]])

In [ ]:
a3 + m1 # [m1, m1, m1] -> 3차원 축확장

ValueError: ignored

In [ ]:
zl = [1,1,1,1,1,1]
m2 = np.array(l).reshape(3,2,1)
m2

array([[[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]]])

In [ ]:
a3 + m2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

연결

In [ ]:
[1,1,1]+[2,3,4]

[1, 1, 1, 2, 3, 4]

In [ ]:
v1 = np.array([1,1,1])
v2 = np.array([2,2,2])
np.hstack([v1,v2])
a2 = np.vstack([v1,v2])
a3 = np.vstack([v1,v2])
np.vstack([a2,v1])

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

In [ ]:
a4 = a2.reshape(1,2,3)
a5 = a3.reshape(1,2,3)
a4, a5

(array([[[1, 1, 1],
         [2, 2, 2]]]),
 array([[[1, 1, 1],
         [2, 2, 2]]]))

In [ ]:
a6 = np.vstack([a4, a5])

In [ ]:
a4.shape, a6.shape

((1, 2, 3), (2, 2, 3))

In [ ]:
np.vstack([a4, a6])

array([[[1, 1, 1],
        [2, 2, 2]],

       [[1, 1, 1],
        [2, 2, 2]],

       [[1, 1, 1],
        [2, 2, 2]]])

In [ ]:
#np.concatenate 함수
#축을 고려하여 붙임 (차원수 맞춰야함)

Y = WX
- y1 = 10x
- y2 = 20x
- y3 = 30x<br>
X = [1,2,3]

In [ ]:
X = [1, 2, 3]
W = [10, 20, 30]
np_X = np.array(X)
np_W = np.array(W)
np_X * np_W

array([10, 40, 90])

In [ ]:
heights = np.array([1.83, 1.76, 1.69, 1.86, 1.77, 1.73])
weights = np.array([86, 74, 59, 95, 80, 68])
bmi = weights / heights ** 2
np.set_printoptions(precision = 2, suppress = True)
print(bmi)

[25.68 23.89 20.66 27.46 25.54 22.72]


random

In [ ]:
#np.random.randint(1,11,100) #최소, 최대, shape
np.round(np.random.uniform(1,10,100), 2)

array([5.19, 5.58, 3.84, 8.64, 8.29, 8.19, 5.15, 3.92, 8.42, 1.63, 9.07,
       5.88, 4.42, 7.8 , 6.27, 6.77, 6.17, 8.62, 1.35, 5.25, 1.41, 2.09,
       7.75, 7.66, 5.26, 4.86, 6.71, 3.55, 8.68, 2.77, 8.82, 5.43, 7.48,
       2.72, 5.91, 4.11, 9.72, 3.51, 5.31, 8.96, 2.26, 7.83, 4.27, 8.33,
       2.8 , 5.91, 7.6 , 3.09, 1.84, 6.31, 7.52, 1.63, 3.08, 8.39, 3.59,
       4.9 , 5.24, 4.81, 6.09, 2.42, 6.01, 7.78, 5.41, 1.73, 8.75, 2.54,
       1.63, 6.78, 3.42, 9.42, 8.81, 7.83, 9.75, 7.14, 1.72, 1.65, 3.3 ,
       4.13, 2.9 , 7.19, 8.04, 5.38, 9.48, 9.85, 8.09, 6.61, 9.39, 2.52,
       7.09, 3.7 , 8.27, 7.16, 1.71, 6.02, 6.77, 2.77, 8.29, 9.65, 4.86,
       5.07])

seed()

In [ ]:
np.random.seed(1)
#np.round(np.random.uniform(1,10,10), 2)
w = np.random.randint(40, 100, 100)
h = np.random.uniform(1.5, 2, 100)

In [ ]:
bmi = np.round(w/(h*h),1)
bmi

array([24. , 26.1, 15.9, 12.3, 18.4, 19.5, 14.4, 14.1, 13.1, 17.9, 11.6,
       22.4, 19.1, 23.6, 20. , 17.2, 28.7, 20.2, 20.3, 20.3, 19.2, 15.3,
       29. , 21.3, 20.9, 22.1, 26.4, 13.2, 22.4, 17.8, 28.8, 25.3, 25.2,
       30.9, 23.5, 26.2, 14.8, 34.5, 17.4, 12.1, 21.7, 27.4, 11.5, 14.7,
       16. , 19.3, 20. , 23.4, 26.5, 28.9, 23.1, 32.3, 18. , 19.1, 14.9,
       18.2, 15.3, 17.4, 34.9, 32.3, 16.5, 14.3, 24.9, 38.3, 26.8, 20.7,
       22.9, 38.1, 18.2, 35.3, 33.7, 31. , 14.7, 20.5, 15.3, 18.4, 20.4,
       29.8, 26.1, 17.3, 17.4, 19.1, 19.9, 27.2, 17.6, 16.7, 14.6, 28. ,
       25.3, 19.6, 17.5, 21.5, 29.7, 25.6, 23.4, 19.6, 26.5, 26.2, 18.7,
       26.7])

In [ ]:
bmi < 25

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True, False, False, False, False,  True, False,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
       False, False,  True,  True, False,  True, False, False, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True, False, False,  True,
        True,  True, False, False,  True,  True, False, False,  True,
       False])

In [ ]:
print(bmi[bmi < 25])
len(bmi[bmi < 25])

[24.  15.9 12.3 18.4 19.5 14.4 14.1 13.1 17.9 11.6 22.4 19.1 23.6 20.
 17.2 20.2 20.3 20.3 19.2 15.3 21.3 20.9 22.1 13.2 22.4 17.8 23.5 14.8
 17.4 12.1 21.7 11.5 14.7 16.  19.3 20.  23.4 23.1 18.  19.1 14.9 18.2
 15.3 17.4 16.5 14.3 24.9 20.7 22.9 18.2 14.7 20.5 15.3 18.4 20.4 17.3
 17.4 19.1 19.9 17.6 16.7 14.6 19.6 17.5 21.5 23.4 19.6 18.7]


68

내적(행렬곱)

In [ ]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
print(a1)
print(a2)
np.dot(a1,a2)
a1.dot(a2)
a1@a2

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [ ]:
a1.T

array([[1, 3],
       [2, 4]])

In [ ]:
a1 = np.array([[1,2,3,4]])
a2 = np.array([[5],[6],[7],[8]])
a1 * a2

array([[ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28],
       [ 8, 16, 24, 32]])

In [ ]:
a1 = np.array([[1,2,3,4],
               [1,2,3,4]])
a2 = np.array([[5,5,5],
                [6,6,6],
                [7,7,7],
                [8,8,8]])
a3 = a1@a2

In [ ]:
a3

array([[70, 70, 70],
       [70, 70, 70]])

In [ ]:
tr_a1 = a1.reshape(1,2,4)
tr_a2 = a2.reshape(4,3,1)

In [ ]:
tr_a1.shape,tr_a2.shape

((1, 2, 4), (4, 3, 1))

In [ ]:
X = np.array([[1,2,3],[1,4,7]])
W = np.array([[1, 3, 5],[1, 3, 5]])
X.shape, W.shape

((2, 3), (2, 3))

In [ ]:
W@X.T

array([[22, 48],
       [22, 48]])

In [ ]:
X = np.array([[1,2,3,4]]).T
W = np.array([[2,3,4,5]]).T

In [ ]:
W*X

array([[ 2],
       [ 6],
       [12],
       [20]])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,0],[0,1]])
a@b

array([[1, 2],
       [3, 4]])

In [ ]:
inv_a = np.linalg.inv(a)
inv_a

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
a@inv_a

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.linalg.det(a)

-2.0000000000000004

비교

In [ ]:
a % 2 == 0

array([[False,  True],
       [False,  True]])

논리

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
np.all(a%2 == 0, axis = 0) #and

array([False,  True])

In [ ]:
np.any(a % 2 == 0, axis = 1) #or

array([ True,  True])

In [ ]:
np.all(a - 1)

False

In [ ]:
np.any(a)

True

In [ ]:
student = np.random.randint(0,101,100)
student_mean = np.mean(student)
if student_mean >= 50:
    print("전원 통과")
if len(student[student >= 50]) >= 50:
    print("학년1등반")
if len(student[student == 100]) >= 1:
    print("전교1등반")

전원 통과
학년1등반
전교1등반


In [ ]:
student = np.random.randint(0,101,100)
student_mean = np.mean(student)
if student_mean >= 50:
    print("전원 통과")
if np.all(student >= 50):
    print("학년1등반")
if np.any(student == 100):
    print("전교1등반")

전원 통과


where 함수


In [ ]:
np.where(student >= 50, "합격", "불합격")

array(['불합격', '불합격', '합격', '불합격', '합격', '합격', '불합격', '합격', '불합격', '합격',
       '합격', '불합격', '불합격', '합격', '불합격', '합격', '합격', '불합격', '불합격', '불합격',
       '합격', '합격', '합격', '불합격', '불합격', '합격', '합격', '합격', '합격', '불합격',
       '불합격', '합격', '합격', '합격', '합격', '불합격', '불합격', '불합격', '합격', '불합격',
       '불합격', '불합격', '불합격', '합격', '합격', '합격', '불합격', '불합격', '합격', '합격',
       '불합격', '합격', '불합격', '합격', '불합격', '불합격', '불합격', '합격', '합격', '불합격',
       '합격', '불합격', '불합격', '합격', '불합격', '불합격', '불합격', '합격', '합격', '합격',
       '불합격', '합격', '합격', '합격', '불합격', '합격', '불합격', '불합격', '합격', '합격',
       '합격', '합격', '불합격', '불합격', '불합격', '불합격', '합격', '합격', '합격', '불합격',
       '합격', '불합격', '합격', '합격', '합격', '불합격', '불합격', '합격', '불합격', '합격'],
      dtype='<U3')

In [ ]:
np.argsort(student)

array([52, 66, 19,  3, 56, 59, 89, 62, 74, 76, 54, 35, 30, 55,  0, 12, 64,
       85, 40, 61, 14, 46, 77,  1, 91, 39, 82, 29, 23, 11,  8, 37, 84, 41,
       17, 98, 36, 95, 42, 24, 96, 83, 50, 65, 70, 18,  6, 47, 48, 58, 78,
        5, 71, 51, 87, 67, 80, 90,  7, 33, 49, 63, 21, 32, 26, 13, 60, 31,
       45, 93, 73, 25, 43, 88, 97, 92, 44, 75, 34, 72, 20, 69, 38, 15, 79,
       81,  2, 53, 22, 94, 68, 27, 99, 86, 57, 16, 28,  4, 10,  9])

In [ ]:
sort_student = student[np.argsort(student)]

In [ ]:
student

array([ 19,  26,  86,   7,  99,  53,  47,  60,  34, 100, 100,  32,  19,
        67,  24,  83,  94,  38,  47,   5,  79,  63,  87,  32,  42,  74,
        66,  88,  98,  30,  17,  68,  64,  60,  78,  17,  39,  35,  81,
        28,  22,  38,  41,  74,  77,  70,  25,  48,  50,  62,  44,  54,
         0,  86,  16,  19,   9,  92,  51,  10,  68,  23,  14,  63,  21,
        46,   3,  56,  88,  80,  46,  54,  79,  71,  14,  77,  15,  25,
        53,  84,  58,  85,  29,  44,  37,  22,  91,  54,  76,  12,  59,
        26,  76,  71,  87,  39,  43,  76,  38,  91])

In [ ]:
sort_student

array([  0,   4,   9,  11,  17,  18,  18,  18,  19,  20,  20,  22,  23,
        25,  26,  26,  26,  27,  27,  28,  29,  30,  30,  31,  31,  32,
        35,  36,  38,  38,  38,  38,  38,  41,  42,  45,  48,  50,  51,
        52,  52,  52,  55,  56,  56,  57,  57,  59,  59,  60,  60,  60,
        60,  61,  61,  62,  62,  63,  64,  64,  64,  65,  66,  66,  67,
        68,  68,  68,  69,  69,  70,  70,  71,  72,  74,  75,  76,  76,
        77,  77,  78,  79,  80,  82,  83,  83,  87,  92,  93,  93,  95,
        95,  96,  97,  97,  99,  99, 100, 100, 100])

In [ ]:
student[np.argmax(student)]

100

In [ ]:
student[np.argmin(student)]

0

In [ ]:
a1 = np.array([1,2,3,4])
a1[[True, True, False, False]]

array([1, 2])

In [ ]:
# y = wx + b
실제값 = [30, 50, 90]
x = np.array([[1, 2],[2,3],[4,5]]).T
w = np.array([[10, 10]]).T
b = 0.1
w*x
예측값 = w.T@x + b
예측값

array([[30.1, 50.1, 90.1]])

#판다스

In [4]:
num_d = np.array([[4,5,6],[1,2,3],[8,9,7],[4,6,8]])
num_d

array([[4, 5, 6],
       [1, 2, 3],
       [8, 9, 7],
       [4, 6, 8]])

In [5]:
num_d[0:3:2, 2]

array([6, 7])

In [6]:
num_d[0:3:2, 2:]

array([[6],
       [7]])

In [ ]:
import pandas as pd
from pandas import DataFrame, Series

In [ ]:
s = Series([1,2,3,4], [1,1,2,2])
s

1    1
1    2
2    3
2    4
dtype: int64

In [ ]:
s[2]

2    3
2    4
dtype: int64

In [ ]:
s = Series(['1','2','3','4','5'],[0,1,2,2,3])
print(s)

0    1
1    2
2    3
2    4
3    5
dtype: object


In [ ]:
s.index.name = "num"

In [ ]:
s

num
0    1
1    2
2    3
2    4
3    5
dtype: object

In [ ]:
d = {'a' : 1, 'b' : 1, 'c' : 1, 'd' : 1, 'e' : 1}
Series(d)

a    1
b    1
c    1
d    1
e    1
dtype: int64

In [ ]:
Series(d, 'a b c f g'.split())

a    1.0
b    1.0
c    1.0
f    NaN
g    NaN
dtype: float64

데이터 프레임

In [ ]:
#DataFrame([[1,2,3],[2],[3],[4],[5],[6],[7]])
d = dict.fromkeys([1,2,3,4,5],[1])
print(d)
DataFrame(d)

{1: [1], 2: [1], 3: [1], 4: [1], 5: [1]}


1  2  3  4  5
0  1  1  1  1  1