In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
%%writefile data.csv
연도,1분기,2분기,3분기,4분기
2016,2401,4051,5041,1051
2017,2701,4031,6041,1102
2018,2030,5002,5302,1203
2019,2405,5802,2034,2032
2020,2340,5043,5032,1902

Overwriting data.csv


In [ ]:
f = "data.csv"
df = pd.read_csv(f,encoding = 'utf-8')
df

연도   1분기   2분기   3분기   4분기
0  2016  2401  4051  5041  1051
1  2017  2701  4031  6041  1102
2  2018  2030  5002  5302  1203
3  2019  2405  5802  2034  2032
4  2020  2340  5043  5032  1902

In [ ]:
df.to_csv("tr_data.csv", index = False)

In [ ]:
df = pd.read_csv("tr_data.csv", encoding = 'utf-8')
df

연도   1분기   2분기   3분기   4분기
0  2016  2401  4051  5041  1051
1  2017  2701  4031  6041  1102
2  2018  2030  5002  5302  1203
3  2019  2405  5802  2034  2032
4  2020  2340  5043  5032  1902

In [ ]:
df1 = df['2분기'][1]
df1

4031

In [ ]:
df1 = df[df.columns]
df1

연도   1분기   2분기   3분기   4분기
0  2016  2401  4051  5041  1051
1  2017  2701  4031  6041  1102
2  2018  2030  5002  5302  1203
3  2019  2405  5802  2034  2032
4  2020  2340  5043  5032  1902

In [ ]:
r_df = pd.read_csv('data.csv')
df = r_df[r_df.columns]
df.to_excel("tr_data.xlsx",sheet_name = "이용 고객 수",index = False)
df

연도   1분기   2분기   3분기   4분기
0  2016  2401  4051  5041  1051
1  2017  2701  4031  6041  1102
2  2018  2030  5002  5302  1203
3  2019  2405  5802  2034  2032
4  2020  2340  5043  5032  1902

In [ ]:
# with pd.ExcelWriter("tr_data.xlsx", engine = "xlsxwriter") as f_n:
#     df.to_excel(f_n,sheet_name = "이용 고객 수df",index = False)
#     df.to_excel(f_n,sheet_name = "이용 고객 수df1",index = False)

In [ ]:
df

연도   1분기   2분기   3분기   4분기
0  2016  2401  4051  5041  1051
1  2017  2701  4031  6041  1102
2  2018  2030  5002  5302  1203
3  2019  2405  5802  2034  2032
4  2020  2340  5043  5032  1902

In [ ]:
df['평균'] = df.mean(axis = 1)
df

연도   1분기   2분기   3분기   4분기      평균
0  2016  2401  4051  5041  1051  2912.0
1  2017  2701  4031  6041  1102  3178.4
2  2018  2030  5002  5302  1203  3111.0
3  2019  2405  5802  2034  2032  2858.4
4  2020  2340  5043  5032  1902  3267.4

In [ ]:
df.reindex(columns = [4,1,2,3,0])

4   1   2   3   0
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN

In [ ]:
df1 + df

1분기    2분기    3분기   4분기    연도  평균
0  4802   8102  10082  2102  4032 NaN
1  5402   8062  12082  2204  4034 NaN
2  4060  10004  10604  2406  4036 NaN
3  4810  11604   4068  4064  4038 NaN
4  4680  10086  10064  3804  4040 NaN

In [ ]:
df[:3]

연도   1분기   2분기   3분기   4분기      평균
0  2016  2401  4051  5041  1051  2912.0
1  2017  2701  4031  6041  1102  3178.4
2  2018  2030  5002  5302  1203  3111.0

In [ ]:
df['연도'].dtype

dtype('int64')

In [ ]:
df

연도   1분기   2분기   3분기   4분기      평균
0  2016  2401  4051  5041  1051  2912.0
1  2017  2701  4031  6041  1102  3178.4
2  2018  2030  5002  5302  1203  3111.0
3  2019  2405  5802  2034  2032  2858.4
4  2020  2340  5043  5032  1902  3267.4

In [ ]:
a = [1, 2, 3, 4, 5]
a[1] = 6
a


[1, 6, 3, 4, 5]

In [ ]:
a = [1, 2, 3, 4, 5]
for i in range(6, 11):
    a =
# a = [6, 7, 8, 9, 10]

0    2016
1    2017
2    2018
3    2019
4    2020
Name: 연도, dtype: int64

In [ ]:
df[2, 0]

KeyError: ignored

In [ ]:
t_df = df.reindex([4,1,3,2,0])
t_df

연도   1분기   2분기   3분기   4분기      평균
4  2020  2340  5043  5032  1902  3267.4
1  2017  2701  4031  6041  1102  3178.4
3  2019  2405  5802  2034  2032  2858.4
2  2018  2030  5002  5302  1203  3111.0
0  2016  2401  4051  5041  1051  2912.0

In [ ]:
t_df.loc[1:2, :"1분기"]

연도   1분기
1  2017  2701
3  2019  2405
2  2018  2030

In [ ]:
t_df

연도   1분기   2분기   3분기   4분기      평균
4  2020  2340  5043  5032  1902  3267.4
1  2017  2701  4031  6041  1102  3178.4
3  2019  2405  5802  2034  2032  2858.4
2  2018  2030  5002  5302  1203  3111.0
0  2016  2401  4051  5041  1051  2912.0

In [ ]:
t_df.iloc[0:3, 0:3]

연도   1분기   2분기
4  2020  2340  5043
1  2017  2701  4031
3  2019  2405  5802

In [ ]:
df.iloc[3:, 0]

3    2019
4    2020
Name: 연도, dtype: int64

In [ ]:
df

연도   1분기   2분기   3분기   4분기      평균
0  2016  2401  4051  5041  1051  2912.0
1  2017  2701  4031  6041  1102  3178.4
2  2018  2030  5002  5302  1203  3111.0
3  2019  2405  5802  2034  2032  2858.4
4  2020  2340  5043  5032  1902  3267.4

In [ ]:
df[df["평균"].isin([2723.5])]

Empty DataFrame
Columns: [연도, 1분기, 2분기, 3분기, 4분기, 평균]
Index: []

pandas 통합

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    '경부선ktx' : [1234,76164,156494,1654984,165198],
    '호남선ktx' : [132,654,984,121,48522],
    '경전선ktx' : [156498,67981,1984653,89785461,1894],
    '전라선ktx' : [5465489,16231,13216,165981,6133],
    '동해선ktx' : [189798,98746,123465,61365,6498]
}
p_list = ['경부선ktx', '호남선ktx', '경전선ktx', '전라선ktx', '동해선ktx']
번호 = ['1호기', '2호기', '3호기', '4호기', '5호기']
이용객수 = ['2011', '2012', '2013', '2014', '2015']
end_d = pd.DataFrame(data,index = 이용객수, columns = p_list)
end_d

경부선ktx  호남선ktx    경전선ktx   전라선ktx  동해선ktx
2011     1234     132    156498  5465489  189798
2012    76164     654     67981    16231   98746
2013   156494     984   1984653    13216  123465
2014  1654984     121  89785461   165981   61365
2015   165198   48522      1894     6133    6498

In [ ]:
end_d.index

Index(['2011', '2012', '2013', '2014', '2015'], dtype='object')

In [ ]:
end_d.columns

Index(['경부선ktx', '호남선ktx', '경전선ktx', '전라선ktx', '동해선ktx'], dtype='object')

In [ ]:
end_d.values

array([[    1234,      132,   156498,  5465489,   189798],
       [   76164,      654,    67981,    16231,    98746],
       [  156494,      984,  1984653,    13216,   123465],
       [ 1654984,      121, 89785461,   165981,    61365],
       [  165198,    48522,     1894,     6133,     6498]])

In [ ]:
end_d.head(2)

경부선ktx  호남선ktx  경전선ktx   전라선ktx  동해선ktx
2011    1234     132  156498  5465489  189798
2012   76164     654   67981    16231   98746

In [ ]:
end_d

경부선ktx  호남선ktx    경전선ktx   전라선ktx  동해선ktx
2011     1234     132    156498  5465489  189798
2012    76164     654     67981    16231   98746
2013   156494     984   1984653    13216  123465
2014  1654984     121  89785461   165981   61365
2015   165198   48522      1894     6133    6498

In [ ]:
end_d.loc['2011': '2012', '경부선ktx':'전라선ktx']

경부선ktx  호남선ktx  경전선ktx   전라선ktx
2011    1234     132  156498  5465489
2012   76164     654   67981    16231

In [ ]:
end_d.iloc[0, 0]

1234

In [ ]:
end_d.iloc[:1, 0:]

경부선ktx  호남선ktx  경전선ktx   전라선ktx  동해선ktx
2011    1234     132  156498  5465489  189798

In [ ]:
end_d.iloc[0:3, 0:3]

경부선ktx  호남선ktx   경전선ktx
2011    1234     132   156498
2012   76164     654    67981
2013  156494     984  1984653

In [ ]:
end_d['경부선ktx'][2:3]

2013    156494
Name: 경부선ktx, dtype: int64

In [ ]:
end_d.T

2011   2012     2013      2014    2015
경부선ktx     1234  76164   156494   1654984  165198
호남선ktx      132    654      984       121   48522
경전선ktx   156498  67981  1984653  89785461    1894
전라선ktx  5465489  16231    13216    165981    6133
동해선ktx   189798  98746   123465     61365    6498

병합

In [ ]:
import pandas as pd
import numpy as np

d1 = {
    '기준' : [0, 1, 2, 3, 4, 5],
    "data1" : [4, 5, 2, 3, 4, 5],
    'data2' : ['A', 'B', 'D', 'E', 'F', 'Z']
}
df1 = pd.DataFrame(d1,columns = ['기준','data1','data2'])
df1

기준  data1 data2
0   0      4     A
1   1      5     B
2   2      2     D
3   3      3     E
4   4      4     F
5   5      5     Z

In [ ]:
d2 = {
    '기준' : [2, 4, 9, 3],
    "data1" : [4, 5, 2, 3],
    'data3' : ['data1', 'data2', 'data3', 'data4']
}
df2 = pd.DataFrame(d2,columns = ['기준','data1','data3'])
df2

기준  data1  data3
0   2      4  data1
1   4      5  data2
2   9      2  data3
3   3      3  data4

In [ ]:
df1

기준  data1 data2
0   0      4     A
1   1      5     B
2   2      2     D
3   3      3     E
4   4      4     F
5   5      5     Z

In [ ]:
df2

기준  data1  data3
0   2      4  data1
1   4      5  data2
2   9      2  data3
3   3      3  data4

In [ ]:
pd.merge(df1,df2)

기준  data1 data2  data3
0   3      3     E  data4

In [ ]:
pd.merge(df1,df2,on="기준")

기준  data1_x data2  data1_y  data3
0   2        2     D        4  data1
1   3        3     E        3  data4
2   4        4     F        5  data2

In [ ]:
pd.merge(df1, df2, how = "outer", on = "기준")

기준  data1_x data2  data1_y  data3
0   0      4.0     A      NaN    NaN
1   1      5.0     B      NaN    NaN
2   2      2.0     D      4.0  data1
3   3      3.0     E      3.0  data4
4   4      4.0     F      5.0  data2
5   5      5.0     Z      NaN    NaN
6   9      NaN   NaN      2.0  data3

In [ ]:
pd.merge(df1, df2, how = "left", on = "기준")

기준  data1_x data2  data1_y  data3
0   0        4     A      NaN    NaN
1   1        5     B      NaN    NaN
2   2        2     D      4.0  data1
3   3        3     E      3.0  data4
4   4        4     F      5.0  data2
5   5        5     Z      NaN    NaN

In [ ]:
pd.merge(df1, df2, how = "right", on = "기준")

기준  data1_x data2  data1_y  data3
0   2      2.0     D        4  data1
1   4      4.0     F        5  data2
2   9      NaN   NaN        2  data3
3   3      3.0     E        3  data4

In [ ]:
from numpy.linalg import inv

data1 = [[2, 3], [1, -2]]
data2 = [[1], [4]]

arr1 = np.array(data1)
arr2 = np.array(data2)
result = inv(arr1)@arr2
x = result[0, 0]
y = result[1, 0]
x, y, result


(2.0,
 -1.0,
 array([[ 2.],
        [-1.]]))

In [ ]:
2x + 3y = 1
x - 2y = 4

SyntaxError: ignored

데이터 전처리

시본_데이터

In [ ]:
import seaborn as sns
sns.get_dataset_names()

In [ ]:
df = sns.load_dataset('titanic')
df

In [ ]:
df.info()

In [ ]:
df.isnull().sum()/len(df)*100

In [1]:
df = df.dropna()
df

NameError: ignored